import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ArrowLeft,
  Phone,
  Mail,
  Building2,
  MapPin,
  Cake,
  Link as LinkIcon,
  Sparkles,
  RefreshCw,
  MessageSquareText,
  Pencil,
  Trash2,
  Plus,
} from 'lucide-react';
import {
  useContact,
  useTimeline,
  useTasks,
  useRelationshipSummary,
  useFollowUp,
  useAddNote,
  useUpdateContact,
  useDeleteContact,
} from '@/hooks/useCrm';
import { computeRelationshipBreakdown, formatDate, daysUntilBirthday } from '@/lib/utils';
import Avatar from '@/components/Avatar';
import TagBadge from '@/components/TagBadge';
import RelationshipScore from '@/components/RelationshipScore';
import TimelineItem from '@/components/TimelineItem';
import TypingText from '@/components/TypingText';
import ConversationPrepSheet from '@/components/ConversationPrepSheet';
import ContactFormModal from '@/components/ContactFormModal';

export default function ContactDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data: contact, isLoading } = useContact(id);
  const { data: timeline = [] } = useTimeline(id);
  const { data: allTasks = [] } = useTasks();

  const relationshipSummary = useRelationshipSummary();
  const followUp = useFollowUp();
  const addNote = useAddNote();
  const updateContact = useUpdateContact();
  const deleteContact = useDeleteContact();

  const [prepOpen, setPrepOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [noteText, setNoteText] = useState('');
  const autoGenerated = useRef(false);

  useEffect(() => {
    if (contact && !contact.aiSummary && !autoGenerated.current) {
      autoGenerated.current = true;
      relationshipSummary.mutate(contact.id);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [contact?.id, contact?.aiSummary]);

  if (isLoading) {
    return <div className="nb-card-flat h-64 animate-pulse bg-sunken" />;
  }

  if (!contact) {
    return (
      <div className="nb-card p-8 text-center sm:p-10">
        <p className="font-bold">Contact not found.</p>
        <Link to="/contacts" className="nb-btn mt-4">
          <ArrowLeft size={14} strokeWidth={2.8} /> Back to contacts
        </Link>
      </div>
    );
  }

  const breakdown = computeRelationshipBreakdown(contact, timeline, allTasks);
  const daysToBday = daysUntilBirthday(contact.birthday);

  function handleAddNote(e: React.FormEvent) {
    e.preventDefault();
    if (!noteText.trim() || !contact) return;
    addNote.mutate({ id: contact.id, text: noteText.trim() });
    setNoteText('');
  }

  function handleDelete() {
    if (!contact) return;
    if (!confirm(`Delete ${contact.name}? This can't be undone.`)) return;
    deleteContact.mutate(contact.id, { onSuccess: () => navigate('/contacts') });
  }

  return (
    <div className="space-y-4 sm:space-y-5">
      <Link to="/contacts" className="nb-btn px-2.5 py-1 text-[11px]">
        <ArrowLeft size={13} strokeWidth={2.8} /> Back
      </Link>

      {/* Profile header */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="nb-card p-4 sm:p-6">
        <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div className="flex min-w-0 items-start gap-3 sm:gap-4">
            <Avatar name={contact.name} size="xl" />
            <div className="min-w-0">
              <h1 className="nb-display text-xl leading-tight sm:text-3xl">{contact.name}</h1>
              <p className="mt-1 text-sm font-medium text-muted">
                {contact.position || '—'}
                {contact.company && ` · ${contact.company}`}
              </p>
              <div className="mt-2 flex flex-wrap gap-1.5">
                {contact.tags.map((t) => (
                  <TagBadge key={t} tag={t} />
                ))}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between gap-3 border-t-2 border-dashed border-ink/25 pt-4 md:border-0 md:pt-0">
            <RelationshipScore score={breakdown.total} size={82} />
            <div className="flex flex-col gap-2">
              <button onClick={() => setPrepOpen(true)} className="nb-btn bg-lav text-onaccent">
                <MessageSquareText size={15} strokeWidth={2.8} />
                Conversation Prep
              </button>
              <div className="flex gap-2">
                <button onClick={() => setEditOpen(true)} className="nb-btn flex-1 px-2.5 py-1 text-[11px]">
                  <Pencil size={12} strokeWidth={2.8} /> Edit
                </button>
                <button onClick={handleDelete} className="nb-btn flex-1 bg-coral px-2.5 py-1 text-[11px] text-onaccent">
                  <Trash2 size={12} strokeWidth={2.8} /> Delete
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-2 border-t-2 border-dashed border-ink/25 pt-4 text-sm font-medium xs:grid-cols-2 lg:grid-cols-3">
          {contact.phone && <InfoRow icon={<Phone size={14} strokeWidth={2.6} />} value={contact.phone} />}
          {contact.email && <InfoRow icon={<Mail size={14} strokeWidth={2.6} />} value={contact.email} />}
          {contact.company && <InfoRow icon={<Building2 size={14} strokeWidth={2.6} />} value={contact.company} />}
          {contact.location && <InfoRow icon={<MapPin size={14} strokeWidth={2.6} />} value={contact.location} />}
          {contact.birthday && (
            <InfoRow
              icon={<Cake size={14} strokeWidth={2.6} />}
              value={`${formatDate(contact.birthday)}${
                daysToBday !== null && daysToBday <= 7 ? ` · ${daysToBday === 0 ? 'today 🎂' : `in ${daysToBday}d`}` : ''
              }`}
            />
          )}
          {contact.social.linkedin && (
            <InfoRow icon={<LinkIcon size={14} strokeWidth={2.6} />} value={contact.social.linkedin} />
          )}
        </div>
      </motion.div>

      <div className="grid gap-4 lg:grid-cols-5">
        <div className="space-y-4 lg:col-span-3">
          {/* AI memory */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05 }}
            className="nb-card p-4 sm:p-5"
          >
            <div className="mb-3 flex items-center justify-between gap-2">
              <div className="flex min-w-0 items-center gap-2.5">
                <div className="nb-b grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-lav text-onaccent">
                  <Sparkles size={15} strokeWidth={2.6} />
                </div>
                <h2 className="nb-display text-base sm:text-lg">AI Memory</h2>
              </div>
              <button
                onClick={() => relationshipSummary.mutate(contact.id)}
                disabled={relationshipSummary.isPending}
                className="nb-btn shrink-0 px-2.5 py-1 text-[11px]"
              >
                <RefreshCw
                  size={12}
                  strokeWidth={2.8}
                  className={relationshipSummary.isPending ? 'animate-spin' : ''}
                />
                <span className="hidden xs:inline">Regenerate</span>
              </button>
            </div>

            <div className="mb-3 flex flex-wrap gap-1.5">
              {contact.notes.length === 0 && (
                <span className="text-xs font-medium text-muted">
                  No notes yet — jot down what you remember below.
                </span>
              )}
              {contact.notes.map((n, i) => (
                <span key={`${n}-${i}`} className="nb-card-flat bg-sunken px-2.5 py-1 text-xs font-medium">
                  {n}
                </span>
              ))}
            </div>

            <form onSubmit={handleAddNote} className="mb-4 flex gap-2">
              <input
                value={noteText}
                onChange={(e) => setNoteText(e.target.value)}
                placeholder="e.g. Raising a seed round"
                aria-label="Add a note"
                className="nb-input min-w-0 flex-1 py-1.5 text-xs"
              />
              <button
                type="submit"
                disabled={!noteText.trim() || addNote.isPending}
                className="nb-btn shrink-0 bg-acid px-2.5 py-1.5 text-[11px] text-onaccent"
              >
                <Plus size={12} strokeWidth={2.8} /> Add
              </button>
            </form>

            <div className="nb-card-flat min-h-14 bg-acid p-3 text-sm font-medium leading-relaxed text-onaccent">
              {relationshipSummary.isPending ? (
                <span className="flex items-center gap-2 font-bold">
                  <Sparkles size={14} strokeWidth={2.8} className="animate-pulse" /> Thinking…
                </span>
              ) : relationshipSummary.isSuccess && relationshipSummary.variables === contact.id ? (
                <TypingText text={contact.aiSummary} />
              ) : contact.aiSummary ? (
                contact.aiSummary
              ) : (
                <span className="font-bold">No AI summary yet.</span>
              )}
            </div>

            {!followUp.data && (
              <button
                onClick={() => followUp.mutate(contact.id)}
                disabled={followUp.isPending}
                className="nb-btn mt-3 px-2.5 py-1 text-[11px]"
              >
                {followUp.isPending ? 'Thinking…' : 'Suggest a follow-up'}
              </button>
            )}
            {followUp.data && (
              <p className="nb-card-flat mt-3 bg-sunken p-2.5 text-xs font-medium">
                <span className="nb-label">Follow-up: </span>
                {followUp.data.message}
              </p>
            )}
          </motion.div>

          {/* Timeline */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="nb-card p-4 sm:p-5"
          >
            <h2 className="nb-display mb-4 text-base sm:text-lg">Timeline</h2>
            {timeline.length === 0 ? (
              <p className="text-sm font-medium text-muted">
                No interactions logged yet. Log one from Meeting Notes.
              </p>
            ) : (
              <div>
                {timeline.map((e, i) => (
                  <TimelineItem key={e.id} event={e} isLast={i === timeline.length - 1} />
                ))}
              </div>
            )}
          </motion.div>
        </div>

        <div className="lg:col-span-2">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.15 }}
            className="nb-card p-4 sm:p-5"
          >
            <h2 className="nb-display mb-4 text-base sm:text-lg">Score Breakdown</h2>
            <ScoreBar label="Last Interaction" weight="40%" value={breakdown.recency} accent="bg-acid" />
            <ScoreBar label="Meeting Frequency" weight="30%" value={breakdown.frequency} accent="bg-lav" />
            <ScoreBar label="Completed Tasks" weight="20%" value={breakdown.taskCompletion} accent="bg-aqua" />
            <ScoreBar label="Notes Count" weight="10%" value={breakdown.notes} accent="bg-bubble" />
          </motion.div>
        </div>
      </div>

      <ConversationPrepSheet
        contactId={contact.id}
        contactName={contact.name}
        open={prepOpen}
        onClose={() => setPrepOpen(false)}
      />

      <ContactFormModal
        open={editOpen}
        onClose={() => setEditOpen(false)}
        initial={contact}
        submitting={updateContact.isPending}
        onSubmit={(data) => updateContact.mutate({ id: contact.id, data }, { onSuccess: () => setEditOpen(false) })}
      />
    </div>
  );
}

function InfoRow({ icon, value }: { icon: React.ReactNode; value: string }) {
  return (
    <div className="flex min-w-0 items-center gap-2">
      <span className="nb-b grid h-6 w-6 shrink-0 place-items-center rounded bg-sunken">{icon}</span>
      <span className="truncate">{value}</span>
    </div>
  );
}

function ScoreBar({
  label,
  weight,
  value,
  accent,
}: {
  label: string;
  weight: string;
  value: number;
  accent: string;
}) {
  return (
    <div className="mb-3.5 last:mb-0">
      <div className="mb-1.5 flex items-center justify-between gap-2">
        <span className="text-sm font-bold">
          {label} <span className="nb-label text-muted">({weight})</span>
        </span>
        <span className="text-xs font-bold tabular-nums">{value}%</span>
      </div>
      <div className="nb-b h-4 w-full overflow-hidden rounded-full bg-sunken">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          transition={{ duration: 0.8, ease: 'easeOut' }}
          className={`h-full ${accent}`}
        />
      </div>
    </div>
  );
}
